#!/usr/bin/env python3

import sys
DNA=sys.argv[1]

# --- ITEM 6. Counting characters from a string

# DNA='GATGGGATTggggttttccccTCCCATGTGCTCAAGACTGGCGCTaaaaGttttGAGCTTCTCaaaaGTCTAGAGCCACCGTCCAGGGAGCAGGTAGCTGCTGGGCTCCggggACACTTTGCGTTCGGGCTGGGAGCGTGCTTTCCACGACGGTGACACGCTTCCCTGGATTGGCAGCCAGACTGCCTTCCGGGTCACTGCCATGGAGGAGCCGCAGTCAGATCCTAGCGTCGAGccccCTCTGAGTCAGGAAACAttttCAGACCTATGGAAACTACTTCCTGaaaaCAACGTTCTGTccccCTTGCCGTCCCAAGCAATGGATGATTTGATGCTGTccccGGACGATATTGAACAATGGTTCACTGAAGACCCAGGTCCAGATGAAGCTCCCAGAATTCGCCAGAGGCTGCTccccCCGTGGccccTGCACCAGCAGCTCCTACACCGGCGGccccTGCACCAGccccCTCCTGGccccTGTCATCTTCTGTCCCTTCCCAGaaaaCCTACCAGGGCAGCTACGGTTTCCGTCTGGGCTTCTTGCATTCTGGGACAGCCAAGTCTGTGACTTGCACGTACTccccTGCCCTCAACAAGATGttttGCCAACTGGCCAAGACCTGCCCTGTGCAGCTGTGGGTTGATTCCACAccccCGCCCGGCACCCGCGTCCGCGCCATGGCCATCTACAAGCAGTCACAGCACATGACGGAGGTTGTGAGGCGCTGccccCACCATGAGCGCTGCTCAGATAGCGATGGTCTGGccccTCCTCAGCATCTTATCCGAGTGGAAGGAAATTTGCGTGTGGAGTATTTGGATGACAGAAACACttttCG'

DNA_uppercase=DNA.upper()

freqA=DNA_uppercase.count('A')
freqT=DNA_uppercase.count('T')
freqC=DNA_uppercase.count('C')
freqG=DNA_uppercase.count('G')

print(f'The frequency of A is {freqA}, for T is {freqT}, for C is {freqC}, and for G is {freqG}')




# -----ITEM 7. Replace

RNA=DNA.replace('T','U')
print(f'The T in the sequence {DNA} was replaced with U and now looks like {RNA}')

# ---- ITEM 8. Find and replace
RNA2=DNA.replace('T','U').replace('t', 'u')

print(f'The T or t in the sequence {DNA} was replaced with U or u  and now looks like {RNA2}')
