#!/usr/bin/env python3

DNA='GATGGGATTGGGGTTTTCCCCTCCCATGTGCTCAAGACTGGCGCTAAAAGTTTTGAGCTTCTCAAAAGTCTAGAGCCACCGTCCAGGGAGCAGGTAGCTGCTGGGCTCCGGGGACACTTTGCGTTCGGGCTGGGAGCGTGCTTTCCACGACGGTGACACGCTTCCCTGGATTGGCAGCCAGACTGCCTTCCGGGTCACTGCCATGGAGGAGCCGCAGTCAGATCCTAGCGTCGAGCCCCCTCTGAGTCAGGAAACATTTTCAGACCTATGGAAACTACTTCCTGAAAACAACGTTCTGTCCCCCTTGCCGTCCCAAGCAATGGATGATTTGATGCTGTCCCCGGACGATATTGAACAATGGTTCACTGAAGACCCAGGTCCAGATGAAGCTCCCAGAATTCGCCAGAGGCTGCTCCCCCCGTGGCCCCTGCACCAGCAGCTCCTACACCGGCGGCCCCTGCACCAGCCCCCTCCTGGCCCCTGTCATCTTCTGTCCCTTCCCAGAAAACCTACCAGGGCAGCTACGGTTTCCGTCTGGGCTTCTTGCATTCTGGGACAGCCAAGTCTGTGACTTGCACGTACTCCCCTGCCCTCAACAAGATGTTTTGCCAACTGGCCAAGACCTGCCCTGTGCAGCTGTGGGTTGATTCCACACCCCCGCCCGGCACCCGCGTCCGCGCCATGGCCATCTACAAGCAGTCACAGCACATGACGGAGGTTGTGAGGCGCTGCCCCCACCATGAGCGCTGCTCAGATAGCGATGGTCTGGCCCCTCCTCAGCATCTTATCCGAGTGGAAGGAAATTTGCGTGTGGAGTATTTGGATGACAGAAACACTTTTCG'

EcorRI_segments=DNA.split('GAATTC')
cut_EcoRI_segs=len(EcorRI_segments)


start_pos=len(EcorRI_segments[0])
end_pos=start_pos+6


# --- Other option with find function

indexPos=DNA.find('GAATTC')

starPos=indexPos+1
endPos=starPos+6

print(f'EcoRI startPo:{starPos} endPos:{endPos}')


if indexPos==DNA.find('GAATTC'):
  starPos=indexPos+1
  endPos=starPos+6
  print(f'In the sequence: EcoRI startPo:{starPos} endPos:{endPos}')
elif indexPos==DNA.find('CTTAAG'):
  starPos=indexPos+1
  endPos=starPos+6
  print(f'The sequence is a complement: EcoRI startPo:{starPos} endPos:{endPos}')
else:
  print(f'There is no cut site for EcoRI in this sequence')

