#!/usr/bin/env python3

# Problem 1


''''
Create a function to format a string of DNA so that each line is no more than 60 nt long. 
Your function will:
INPUT: a string of DNA without newlines
OUTPUT: a string of DNA with lines no more than 60 nucleoties lon

'''
import sys
import re

def DNA_format (dna):
    if re.findall(r'[ATGC].+', dna):
        lines = re.findall(r'(.{60})', dna)
        DNA_new= '\n'.join(lines)
    else:
        print('Input most be a DNA sequence (str)')
        exit()
    return DNA_new

DNA = sys.argv[1]
# DNA = 'GATGGGATTGGGGTTTTCCCCTCCCATGTGCTCAAGACTGGCGCTAAAAGTTTTGAGCTTCTCAAAAGTCTAGAGCCACCGTCCAGGGAGCAGGTAGCTGCTGGGCTCCGGGGACACTTTGCGTTCGGGCTGGGAGCGTGCTTTCCACGACGGTGACACGCTTCCCTGGATTGGCAGCCAGACTGCCTTCCGGGTCACTGCCATGGAGGAGCCGCAGTCAGATCCTAGCGTCGAGCCCCCTCTGAGTCAGGAAACATTTTCAGACCTATGGAAACTACTTCCTGAAAACAACGTTCTGTCCCCCTTGCCGTCCCAAGCAATGGATGATTTGATGCTGTCCCCGGACGATATTGAACAATGGTTCACTGAAGACCCAGGTCCAGATGAAGCTCCCAGAATGCCAGAGGCTGCTCCCCCCGTGGCCCCTGCACCAGCAGCTCCTACACCGGCGGCCCCTGCACCAGCCCCCTCCTGGCCCCTGTCATCTTCT'


print(DNA_format(DNA))